language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: SYMFONY_VERSION="~2.3.0" SYMFONY_DEPRECATIONS_HELPER=strict
    - php: 5.5
      env: SYMFONY_VERSION="~2.7.0"
    - php: 5.5
      env: SYMFONY_VERSION="3.0.x-dev as 2.7"
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION="3.0.x-dev as 2.7"

before_script:
    - composer self-update # Update composer as travis is not updating it.
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - composer update

script:
  - bin/phpunit --coverage-clover=coverage.clover -d zend.enable_gc=0
