language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.6.*"
    - SYMFONY_VERSION="2.7.x-dev"

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION="2.7.x-dev"

before_script:
    - composer self-update # Update composer as travis is not updating it.
    - >
        composer require --dev \
          symfony/symfony:${SYMFONY_VERSION}
    - phpenv rehash

script:
  - bin/phpunit --coverage-clover=coverage.clover -d zend.enable_gc=0
